"""initial schema

Revision ID: c6e5060e7328
Revises: 
Create Date: 2026-09-08 04:24:28.321474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e5060e7328'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=254), nullable=False),
    sa.Column('PasswordHash', sa.String(length=254), nullable=False),
    sa.Column('UserRole', sa.Enum('admin', 'lab_manager', 'lab_ta', 'lab_member', 'visitor', name='user_role'), nullable=False),
    sa.Column('UserOrganization', sa.String(length=150), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
