"""empty message

Revision ID: 2c89e76a2e3f
Revises: 
Create Date: 2026-09-07 13:51:07.149102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c89e76a2e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('Username', sa.String(length=100), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('LastName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
