"""equipment type + nullable fk

Revision ID: c3c83ae309bd
Revises: ee5c6d374b75
Create Date: 2026-09-10 16:48:30.168880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3c83ae309bd'
down_revision = 'ee5c6d374b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Equipment', schema=None) as batch_op:
        batch_op.alter_column('EquipmentType',
               existing_type=mysql.ENUM('...'),
               type_=sa.Enum('Usable', 'Unusable', name='equipment_type'),
               existing_nullable=False)

    with op.batch_alter_table('Files', schema=None) as batch_op:
        batch_op.alter_column('FilePath',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)

    with op.batch_alter_table('Request', schema=None) as batch_op:
        batch_op.alter_column('EquipmentID',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Request', schema=None) as batch_op:
        batch_op.alter_column('EquipmentID',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Files', schema=None) as batch_op:
        batch_op.alter_column('FilePath',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)

    with op.batch_alter_table('Equipment', schema=None) as batch_op:
        batch_op.alter_column('EquipmentType',
               existing_type=sa.Enum('Usable', 'Unusable', name='equipment_type'),
               type_=mysql.ENUM('...'),
               existing_nullable=False)

    # ### end Alembic commands ###
