"""add models

Revision ID: ee5c6d374b75
Revises: c6e5060e7328
Create Date: 2026-09-10 15:22:10.946592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5c6d374b75'
down_revision = 'c6e5060e7328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Equipment',
    sa.Column('EquipmentID', sa.Integer(), nullable=False),
    sa.Column('EquipmentName', sa.String(length=140), nullable=False),
    sa.Column('EquipmentModel', sa.String(length=140), nullable=True),
    sa.Column('EquipmentState', sa.Enum('available', 'in_use', 'maintenance', 'retired', name='equipment_state'), nullable=False),
    sa.Column('EquipmentType', sa.Enum('...', name='equipment_type'), nullable=False),
    sa.Column('EquipmentDescription', sa.Text(), nullable=True),
    sa.Column('ReturnAt', sa.String(length=140), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('EquipmentID')
    )
    op.create_table('Activity_log',
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Action', sa.Enum('create', 'update', 'delete', name='log_action'), nullable=False),
    sa.Column('EntityType', sa.Enum('request', 'equipment', 'user', 'file', 'comment', name='log_entity'), nullable=False),
    sa.Column('EntityID', sa.Integer(), nullable=False),
    sa.Column('OldValue', sa.JSON(), nullable=True),
    sa.Column('NewValue', sa.JSON(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    with op.batch_alter_table('Activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Activity_log_EntityID'), ['EntityID'], unique=False)

    op.create_table('Request',
    sa.Column('RequestID', sa.Integer(), nullable=False),
    sa.Column('RequestTitle', sa.String(length=255), nullable=False),
    sa.Column('RequestDetails', sa.Text(), nullable=True),
    sa.Column('RequestState', sa.Enum('pending', 'approved', 'rejected', 'returned', name='request_state'), nullable=False),
    sa.Column('AprovedBy', sa.String(length=255), nullable=True),
    sa.Column('RequestPriority', sa.Enum('low', 'medium', 'high', name='request_priority'), nullable=False),
    sa.Column('RequestDeadline', sa.DateTime(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('EquipmentID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EquipmentID'], ['Equipment.EquipmentID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('RequestID')
    )
    op.create_table('Comments',
    sa.Column('CommentID', sa.Integer(), nullable=False),
    sa.Column('CommentText', sa.Text(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('RequestID', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['RequestID'], ['Request.RequestID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('CommentID')
    )
    op.create_table('Files',
    sa.Column('FileID', sa.Integer(), nullable=False),
    sa.Column('FileName', sa.String(length=100), nullable=False),
    sa.Column('FilePath', sa.String(length=512), nullable=False),
    sa.Column('RequestID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('FileSize', sa.Integer(), nullable=True),
    sa.Column('FileType', sa.String(length=100), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['RequestID'], ['Request.RequestID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('FileID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Files')
    op.drop_table('Comments')
    op.drop_table('Request')
    with op.batch_alter_table('Activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Activity_log_EntityID'))

    op.drop_table('Activity_log')
    op.drop_table('Equipment')
    # ### end Alembic commands ###
