services:
  node-app:
    build:
      context: ./VaseLabNext
    user: 'node'
    working_dir: /home/node/app
    ports: # connect port 3000 in the container to port 3000 in the real world
      - '3000:3000'
    depends_on:
      - flask-app
    networks:
      - backend
    # command: ["bash", "start_prod.sh"]

  flask-app:
    build:
      context: ./VaseLabFlask
    user: 'python'
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - backend
      - db
    volumes:
      - ./VaseLabFlask/migrations:/usr/src/app/migrations
    post_start:
      - command: /venv/bin/python3 -m flask db upgrade
    # command: ["/venv/bin/python3", "-m", "gunicorn", "-w", "4", "-b", "0.0.0.0", "main:create_app()"]


  mysql-db:
    image: mysql:26
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - db

networks:
  backend:
    driver: bridge
  db:
    driver: bridge

volumes:
  db_data: